# Shopify App Configuration
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pricepilotpro"
client_id = "ba170c28db4ad8d6496eb2bd0d6a48ec"
application_url = "https://bulk-price-kappa.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_price_rules,write_price_rules"

[auth]
redirect_urls = [
  "https://bulk-price-kappa.vercel.app/api/auth/callback",
  "http://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/api/webhooks/app-uninstalled"

[[webhooks.subscriptions]]
topics = [ "app_subscriptions/update" ]
uri = "/api/webhooks/app-subscriptions-update"

[pos]
embedded = false
